# Generated by Django 5.2.6 on 2025-09-12 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('ART', 'Arts'), ('SCI', 'Science'), ('COM', 'Commerce'), ('CIV', 'Civil Engineering'), ('ELE', 'Electrical Engineering'), ('CSE', 'Computer Engineering'), ('MEC', 'Mechanical Engineering'), ('ECE', 'Electronics Engineering')], max_length=3)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.question')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('field', models.CharField(choices=[('ART', 'Arts'), ('SCI', 'Science'), ('COM', 'Commerce'), ('CIV', 'Civil Engineering'), ('ELE', 'Electrical Engineering'), ('CSE', 'Computer Engineering'), ('MEC', 'Mechanical Engineering'), ('ECE', 'Electronics Engineering')], max_length=3)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
                ('selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.option')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessmentsession')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_field', models.CharField(choices=[('ART', 'Arts'), ('SCI', 'Science'), ('COM', 'Commerce'), ('CIV', 'Civil Engineering'), ('ELE', 'Electrical Engineering'), ('CSE', 'Computer Engineering'), ('MEC', 'Mechanical Engineering'), ('ECE', 'Electronics Engineering')], max_length=3)),
                ('scores', models.JSONField(default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessments.assessmentsession')),
            ],
        ),
    ]
